encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path('CSS', views.CSS, name='CSS'),
    path('Django', views.Django, name='Django'),
    path('Git', views.Git, name='Git'),
    path('Python', views.Python, name='Python'),
    path('HTML', views.HTML, name='HTML')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def CSS(request):
    return render(request, 'encyclopedia/CSS.html')

def Django(request):
    return render(request, 'encyclopedia/Django.html')

def Git(request):
    return render(request, 'encyclopedia/Git.html')

def HTML(request):
    return render(request, 'encyclopedia/HTML.html')

def Python(request):
    return render(request, 'encyclopedia/Python.html')

encyclopedia/templates/encyclopedia/CSS.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    CSS
{% endblock %}

{% block body %}
    <h1>CSS</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/Django.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    CSS
{% endblock %}

{% block body %}
    <h1>Django</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/Git.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    CSS
{% endblock %}

{% block body %}
    <h1>Git</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/HTML.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    CSS
{% endblock %}

{% block body %}
    <h1>HTML</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/Python.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    CSS
{% endblock %}

{% block body %}
    <h1>Python</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>